openapi: 3.0.0
info:
  title: Node Mongo Boilerplate API
  description: API documentation for Node Mongo Boilerplate project
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Development server
paths:
  /api/users/signup:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                imageUrl:
                  type: string
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Email already taken
        '500':
          description: Server error
